
jump_y_speed = 10.0

[debug]
physics = false

[wheel]
torque_multiplier = -1.6
angular_damping = 0.8
linear_damping = 0.0

[tube]
torque_multiplier = 0.004
angular_damping = 10.0
linear_damping = 0.0
max_angular_velocity = 2.0
mass = 0.01
length = 1.8

[camera]
# playing_scale_divisor = 24.0
units_per_window_height = 30.0

[torso]
width = 2.0
height = 1.5
sprite_height = 1.5
sprite_width = 2.2
death_force = 5.0
mass = 0.004
gravity_scale = 0.125

[head]
x = 0.0
y = 1.42
width = 1.8
height = 1.8

[eyes]
x = 0.0
y = 0.20
width = 0.9
height = 0.6

[arms]
length = 1.5
width = 0.60
angular_damping = 2.0
detach_force = 3.5
mass = 0.001
left.socket.point = { x = -0.9, y = 0.4 }
right.socket.point = { x = 0.9, y = 0.4 }

[editor]
camera_speed = 70.0
grid_size = 1.0

[background]
# scale_x = 40.0
# scale_y = 40.0
scale_x = 40.0
scale_y = 40.0
parallax_x = 0.5
parallax_y = 0.5

[background2]
scale_x = 75.0
scale_y = 75.0
parallax_x = 0.25
parallax_y = 0.25

[wall]
scale_x = 4.0
scale_y = 4.0

[checkpoint]
size = { x = 1.5, y = 7.0 }
collider.pos = { x = 0.0, y = 3.5 }
collider.size = { x = 1.5, y = 7.0 }


[checkpoint.light]
size = { x = 2.0, y = 2.0 }
pos = { x = 0.0, y = 7.9 }
lit_color = { r = 1.0, g = 1.0, b = 0.8 }
unlit_color = { r = 0.3, g = 0.3, b = 0.3 }

[goal]
size = { x = 15.0, y = 12.0 }
collider.pos = { x = 0.0, y = 7.5 }
collider.size = { x = 8.0, y = 12.0 }

[space_tutorial]
size = { x = 16.0, y = 4.0 }

[arrow_tutorial]
size = { x = 8.0, y = 4.0 }

[arrow]
frame_interval = 1.0
size = { x = 5.0, y = 2.0 }

[game_time]
ratio = 16.0

[audio]
soundtrack_volume = 0.15
sfx_volume = 1.0
engine = 0.25
engine_acc = 2.0
engine_dec = 1.0
button = 0.5
jump = 0.5
clonk = 0.5
